### Teste 1: Tentar comprar quantidade negativa (Forçar Erro 400)
POST http://localhost:8080/buy
Content-Type: application/json

{
  "userId": 1,
  "ticker": "AAPL",
  "quantity": -5
}

### Ver Portfolio (GET)
GET http://localhost:8080/portfolio/1

### Ver Historico (GET)
GET http://localhost:8080/history/1

### Registar User (POST)
POST http://localhost:8080/register
Content-Type: application/json

{
    "username": "TiagoInvestidor"
}